//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SampleClassLibrary
{
    #region コンテキスト
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    public partial class UnitTestSampleModelContainer : ObjectContext
    {
        #region コンストラクター
    
        /// <summary>
        /// アプリケーション構成ファイルの 'UnitTestSampleModelContainer' セクションにある接続文字列を使用して新しい UnitTestSampleModelContainer オブジェクトを初期化します。
        /// </summary>
        public UnitTestSampleModelContainer() : base("name=UnitTestSampleModelContainer", "UnitTestSampleModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい UnitTestSampleModelContainer オブジェクトを初期化します。
        /// </summary>
        public UnitTestSampleModelContainer(string connectionString) : base(connectionString, "UnitTestSampleModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい UnitTestSampleModelContainer オブジェクトを初期化します。
        /// </summary>
        public UnitTestSampleModelContainer(EntityConnection connection) : base(connection, "UnitTestSampleModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分メソッド
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<SampleText> SampleTexts
        {
            get
            {
                if ((_SampleTexts == null))
                {
                    _SampleTexts = base.CreateObjectSet<SampleText>("SampleTexts");
                }
                return _SampleTexts;
            }
        }
        private ObjectSet<SampleText> _SampleTexts;

        #endregion

        #region AddTo メソッド
    
        /// <summary>
        /// SampleTexts EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToSampleTexts(SampleText sampleText)
        {
            base.AddObject("SampleTexts", sampleText);
        }

        #endregion

    }

    #endregion

    #region エンティティ
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UnitTestSampleModel", Name="SampleText")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SampleText : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい SampleText オブジェクトを作成します。
        /// </summary>
        /// <param name="id">Id プロパティの初期値。</param>
        /// <param name="text">Text プロパティの初期値。</param>
        public static SampleText CreateSampleText(global::System.Int64 id, global::System.String text)
        {
            SampleText sampleText = new SampleText();
            sampleText.Id = id;
            sampleText.Text = text;
            return sampleText;
        }

        #endregion

        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion

    
    }

    #endregion

    
}
